# Exploration

In [65]:
import plotly.express as px
import plotly.graph_objects as go
import geopandas as gpd

import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

import sqlalchemy

import mysql.connector


import os

os.chdir(r"E:\Karla\IRELAND v2\DKIT\2nd Semester\Data Visualization\CA\CA2\1 Data collection and preparation\Datasets")

In [5]:
# Call stored procedure
df = pd.read_csv("bikes_history.csv")

In [6]:
df.head()

HarvestTime  BikeID  Battery  BikeIdentifier BikeTypeName  \
0  2020-09-23T17:00:02       5     90.0               1  DUB-General   
1  2020-09-23T17:00:02       6     46.0               2  DUB-General   
2  2020-09-23T17:00:02       8      NaN               4  DUB-General   
3  2020-09-23T17:00:02       9     68.0               5  DUB-General   
4  2020-09-23T17:00:02      12     61.0               8  DUB-General   

   EBikeProfileID  EBikeStateID  IsEBike  IsMotor  IsSmartLock  \
0               1             2     True    False        False   
1               1             2     True    False        False   
2               1             2     True    False        False   
3               1             2     True    False        False   
4               1             2     True    False        False   

           LastGPSTime      LastRentalStart  Latitude  Longitude  SpikeID  
0  2020-09-23T17:46:16  2020-09-23T15:34:58   53.3334   -6.24431        1  
1  2020-09-23T17:44:16  2020-09-23T17:35:42   53.3414   -6.28357        2  
2  2020-09-23T11:44:01  2020-09-23T10:17:17    0.0000    0.00000        4  
3  2020-09-23T17:51:29  2020-09-22T07:48:40   53.3252   -6.25521        5  
4  2020-09-23T17:56:10  2020-09-23T17:43:14   53.3090   -6.21631        8

In [9]:
df.BikeID = df.BikeID.astype(str)
df.LastRentalStart = pd.to_datetime(df.LastRentalStart)

In [11]:
df.head()

HarvestTime BikeID  Battery  BikeIdentifier BikeTypeName  \
0  2020-09-23T17:00:02      5     90.0               1  DUB-General   
1  2020-09-23T17:00:02      6     46.0               2  DUB-General   
2  2020-09-23T17:00:02      8      NaN               4  DUB-General   
3  2020-09-23T17:00:02      9     68.0               5  DUB-General   
4  2020-09-23T17:00:02     12     61.0               8  DUB-General   

   EBikeProfileID  EBikeStateID  IsEBike  IsMotor  IsSmartLock  \
0               1             2     True    False        False   
1               1             2     True    False        False   
2               1             2     True    False        False   
3               1             2     True    False        False   
4               1             2     True    False        False   

           LastGPSTime     LastRentalStart  Latitude  Longitude  SpikeID  
0  2020-09-23T17:46:16 2020-09-23 15:34:58   53.3334   -6.24431        1  
1  2020-09-23T17:44:16 2020-09-23 17:35:42   53.3414   -6.28357        2  
2  2020-09-23T11:44:01 2020-09-23 10:17:17    0.0000    0.00000        4  
3  2020-09-23T17:51:29 2020-09-22 07:48:40   53.3252   -6.25521        5  
4  2020-09-23T17:56:10 2020-09-23 17:43:14   53.3090   -6.21631        8

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 814970 entries, 0 to 814969
Data columns (total 15 columns):
 #   Column           Non-Null Count   Dtype         
---  ------           --------------   -----         
 0   HarvestTime      814970 non-null  object        
 1   BikeID           814970 non-null  object        
 2   Battery          792496 non-null  float64       
 3   BikeIdentifier   814970 non-null  int64         
 4   BikeTypeName     814970 non-null  object        
 5   EBikeProfileID   814970 non-null  int64         
 6   EBikeStateID     814970 non-null  int64         
 7   IsEBike          814970 non-null  bool          
 8   IsMotor          814970 non-null  bool          
 9   IsSmartLock      814970 non-null  bool          
 10  LastGPSTime      814970 non-null  object        
 11  LastRentalStart  814970 non-null  datetime64[ns]
 12  Latitude         814970 non-null  float64       
 13  Longitude        814970 non-null  float64       
 14  SpikeID          814

In [13]:
df.head()

HarvestTime BikeID  Battery  BikeIdentifier BikeTypeName  \
0  2020-09-23T17:00:02      5     90.0               1  DUB-General   
1  2020-09-23T17:00:02      6     46.0               2  DUB-General   
2  2020-09-23T17:00:02      8      NaN               4  DUB-General   
3  2020-09-23T17:00:02      9     68.0               5  DUB-General   
4  2020-09-23T17:00:02     12     61.0               8  DUB-General   

   EBikeProfileID  EBikeStateID  IsEBike  IsMotor  IsSmartLock  \
0               1             2     True    False        False   
1               1             2     True    False        False   
2               1             2     True    False        False   
3               1             2     True    False        False   
4               1             2     True    False        False   

           LastGPSTime     LastRentalStart  Latitude  Longitude  SpikeID  
0  2020-09-23T17:46:16 2020-09-23 15:34:58   53.3334   -6.24431        1  
1  2020-09-23T17:44:16 2020-09-23 17:35:42   53.3414   -6.28357        2  
2  2020-09-23T11:44:01 2020-09-23 10:17:17    0.0000    0.00000        4  
3  2020-09-23T17:51:29 2020-09-22 07:48:40   53.3252   -6.25521        5  
4  2020-09-23T17:56:10 2020-09-23 17:43:14   53.3090   -6.21631        8

In [15]:
df.describe()

Battery  BikeIdentifier  EBikeProfileID   EBikeStateID  \
count  792496.000000   814970.000000   814970.000000  814970.000000   
mean       60.079849       57.437826        1.030377       2.049964   
std        23.719765       33.810407        0.300345       0.403718   
min       -12.000000        1.000000        1.000000       1.000000   
25%        44.000000       29.000000        1.000000       2.000000   
50%        67.000000       56.000000        1.000000       2.000000   
75%        78.000000       86.000000        1.000000       2.000000   
max       268.000000      120.000000        4.000000       5.000000   

            Latitude      Longitude        SpikeID  
count  814970.000000  814970.000000  814970.000000  
mean       51.334217      -6.017268      57.437826  
std        10.150329       1.190693      33.810407  
min         0.000000      -6.370620       1.000000  
25%        53.323400      -6.273170      29.000000  
50%        53.343100      -6.257650      56.000000  
75%        53.360800      -6.231830      86.000000  
max        56.184900       0.000000     120.000000

* Battery has to be between 0 and 100, not negative numbers
* other values are ok

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 814970 entries, 0 to 814969
Data columns (total 15 columns):
 #   Column           Non-Null Count   Dtype         
---  ------           --------------   -----         
 0   HarvestTime      814970 non-null  object        
 1   BikeID           814970 non-null  object        
 2   Battery          792496 non-null  float64       
 3   BikeIdentifier   814970 non-null  int64         
 4   BikeTypeName     814970 non-null  object        
 5   EBikeProfileID   814970 non-null  int64         
 6   EBikeStateID     814970 non-null  int64         
 7   IsEBike          814970 non-null  bool          
 8   IsMotor          814970 non-null  bool          
 9   IsSmartLock      814970 non-null  bool          
 10  LastGPSTime      814970 non-null  object        
 11  LastRentalStart  814970 non-null  datetime64[ns]
 12  Latitude         814970 non-null  float64       
 13  Longitude        814970 non-null  float64       
 14  SpikeID          814

In [17]:
df.Battery.isna().sum()

22474

22474 missing values in Battery column

In [19]:
df.IsMotor.unique()

array([False])

In [20]:
df.IsEBike.unique()

array([ True])

In [21]:
df.IsSmartLock.unique()

array([False])

IsMotor, IsEBike and IsSmartLock, drop it as they just have one value, no relevant

In [24]:
df[['BikeID', 'BikeIdentifier', 'SpikeID']]

BikeID  BikeIdentifier  SpikeID
0           5               1        1
1           6               2        2
2           8               4        4
3           9               5        5
4          12               8        8
...       ...             ...      ...
814965    114             110      110
814966    120             101      101
814967    120             101      101
814968    124             120      120
814969    124             120      120

[814970 rows x 3 columns]

BikeID and BikeIdentifier are the same, no make sense to keep them, drop BikeIdentifier. Not clear function of SpikeID in original metadata, therefore, i am going to drop it.

In [26]:
df.EBikeProfileID.unique()

array([1, 4], dtype=int64)

From documentation, it is not clear the function of EBikeProfileID in metadata, therefore i will drop it.

In [28]:
df.drop(columns=['IsMotor', 'IsEBike', 'IsSmartLock', 'BikeIdentifier', 'SpikeID', 'EBikeProfileID'])

HarvestTime BikeID  Battery BikeTypeName  EBikeStateID  \
0       2020-09-23T17:00:02      5     90.0  DUB-General             2   
1       2020-09-23T17:00:02      6     46.0  DUB-General             2   
2       2020-09-23T17:00:02      8      NaN  DUB-General             2   
3       2020-09-23T17:00:02      9     68.0  DUB-General             2   
4       2020-09-23T17:00:02     12     61.0  DUB-General             2   
...                     ...    ...      ...          ...           ...   
814965  2021-05-01T14:30:02    114     86.0  DUB-General             2   
814966  2021-05-01T14:30:02    120     73.0  DUB-General             2   
814967  2021-05-01T14:30:02    120     73.0  DUB-General             2   
814968  2021-05-01T14:30:02    124     72.0  DUB-General             2   
814969  2021-05-01T14:30:02    124     72.0  DUB-General             2   

                LastGPSTime     LastRentalStart  Latitude  Longitude  
0       2020-09-23T17:46:16 2020-09-23 15:34:58   53.3334   -6.24431  
1       2020-09-23T17:44:16 2020-09-23 17:35:42   53.3414   -6.28357  
2       2020-09-23T11:44:01 2020-09-23 10:17:17    0.0000    0.00000  
3       2020-09-23T17:51:29 2020-09-22 07:48:40   53.3252   -6.25521  
4       2020-09-23T17:56:10 2020-09-23 17:43:14   53.3090   -6.21631  
...                     ...                 ...       ...        ...  
814965  2021-05-01T14:20:09 2021-05-01 13:05:21   53.3696   -6.25434  
814966  2021-05-01T14:26:43 2021-04-30 22:14:23   53.3053   -6.21992  
814967  2021-05-01T14:26:43 2021-04-30 22:14:23   53.3053   -6.21992  
814968  2021-05-01T14:27:23 2021-04-27 13:51:23   53.2948   -6.13356  
814969  2021-05-01T14:27:23 2021-04-27 13:51:23   53.2948   -6.13356  

[814970 rows x 9 columns]

It is clear that LastGPSTime and HarvestTime has different values. As there is not good documentation about the MOby API, I assume HarvestTime is the time they collect general data from the bikes and the GPSTime when the gps device retrive the data regarding latitude and longitude. Again, this is not explained by the documentation, therefore this is just an assumtion.

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 814970 entries, 0 to 814969
Data columns (total 15 columns):
 #   Column           Non-Null Count   Dtype         
---  ------           --------------   -----         
 0   HarvestTime      814970 non-null  object        
 1   BikeID           814970 non-null  object        
 2   Battery          792496 non-null  float64       
 3   BikeIdentifier   814970 non-null  int64         
 4   BikeTypeName     814970 non-null  object        
 5   EBikeProfileID   814970 non-null  int64         
 6   EBikeStateID     814970 non-null  int64         
 7   IsEBike          814970 non-null  bool          
 8   IsMotor          814970 non-null  bool          
 9   IsSmartLock      814970 non-null  bool          
 10  LastGPSTime      814970 non-null  object        
 11  LastRentalStart  814970 non-null  datetime64[ns]
 12  Latitude         814970 non-null  float64       
 13  Longitude        814970 non-null  float64       
 14  SpikeID          814

In [64]:
df.loc[:,'HarvestTime'] = pd.to_datetime(df.HarvestTime)
df.loc[:,'LastGPSTime'] = pd.to_datetime(df.LastGPSTime)
df.loc[:,'LastRentalStart'] = pd.to_datetime(df.LastRentalStart)

# Rentals

In [119]:
rentals = df[['LastRentalStart', 'BikeID']].drop_duplicates()

In [120]:
rentals.loc[:,'total'] = 1

In [121]:
rentals.head()

LastRentalStart BikeID  total
0 2020-09-23 15:34:58      5      1
1 2020-09-23 17:35:42      6      1
2 2020-09-23 10:17:17      8      1
3 2020-09-22 07:48:40      9      1
4 2020-09-23 17:43:14     12      1

In [122]:
rentals.set_index('LastRentalStart', inplace=True)

In [124]:
rentalstotal = rentals[['total']].resample('D').sum().reset_index()

In [125]:
fig = px.line(rentalstotal, x='LastRentalStart', y='total')
fig.show()

In [126]:
rentalstotal = rentals[['total']].resample('H').sum().reset_index()

In [127]:
fig = px.line(rentalstotal.set_index('LastRentalStart')['2021-01-01':'2021-01-07'].reset_index(), x='LastRentalStart', y='total')
fig.show()